/** Minimal standards-based OOXML export; emits a real ZIP/DOCX, not HTML renamed .doc. */
const bytes=(s:string)=>new TextEncoder().encode(s);
const xml=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'');
function crc32(data:Uint8Array){let crc=0xffffffff;for(const byte of data){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
function zip(files:Record<string,string>){const parts:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;for(const [name,content]of Object.entries(files)){const n=bytes(name),data=bytes(content),crc=crc32(data),local=new Uint8Array(30+n.length),v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(10,0,true);v.setUint16(12,33,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,n.length,true);local.set(n,30);parts.push(local,data);const entry=new Uint8Array(46+n.length),c=new DataView(entry.buffer);c.setUint32(0,0x02014b50,true);c.setUint16(4,20,true);c.setUint16(6,20,true);c.setUint16(14,33,true);c.setUint32(16,crc,true);c.setUint32(20,data.length,true);c.setUint32(24,data.length,true);c.setUint16(28,n.length,true);c.setUint32(42,offset,true);entry.set(n,46);central.push(entry);offset+=local.length+data.length;}
 const size=central.reduce((n,p)=>n+p.length,0),end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,central.length,true);e.setUint16(10,central.length,true);e.setUint32(12,size,true);e.setUint32(16,offset,true);const output=new Uint8Array(offset+size+22);let pos=0;for(const p of [...parts,...central,end]){output.set(p,pos);pos+=p.length;}return output;}
function paragraph(line:string){const heading=line.match(/^(#{1,3})\s+(.*)$/);const value=heading?heading[2]:line;const runs=value.split(/(\*\*[^*]+\*\*)/g).map(part=>`<w:r>${part.startsWith('**')?'<w:rPr><w:b/></w:rPr>':''}<w:t xml:space="preserve">${xml(part.startsWith('**')?part.slice(2,-2):part)}</w:t></w:r>`).join('');return `<w:p><w:pPr>${heading?`<w:pStyle w:val="Heading${heading[1].length}"/>`:''}<w:spacing w:after="160"/></w:pPr>${runs}</w:p>`;}
export function createDocx(title:string,text:string){return zip({
 '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>',
 '_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
 'word/_rels/document.xml.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 'word/styles.xml':'<?xml version="1.0"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="22"/></w:rPr></w:rPrDefault></w:docDefaults>'+[1,2,3].map((n)=>`<w:style w:type="paragraph" w:styleId="Heading${n}"><w:name w:val="heading ${n}"/><w:pPr><w:keepNext/><w:outlineLvl w:val="${n-1}"/></w:pPr><w:rPr><w:b/><w:sz w:val="${36-n*4}"/></w:rPr></w:style>`).join('')+'</w:styles>',
 'word/document.xml':'<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+paragraph('# '+title)+text.split('\n').map(paragraph).join('')+'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>'
});}
export function downloadDocx(title:string,text:string){const data=createDocx(title,text);const url=URL.createObjectURL(new Blob([data as BlobPart],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}));const a=document.createElement('a');a.href=url;a.download=(title.replace(/[^\p{L}\p{N} _-]/gu,'').slice(0,100)||'legal-eye-document')+'.docx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
