export type PublishedEvidence = { resource_id: string; label: string; text: string };
export type EvidenceCitation = { resource_id: string; label: string; quote: string; page: number | null };
const normalized = (text: string) => text.normalize('NFKC').replace(/\s+/g, ' ').trim();

/** Exact quote presence is a mechanical check, not a finding of legal correctness. */
export function verifyPublishedCitations(citations: EvidenceCitation[], sources: PublishedEvidence[]) {
  return citations.map(citation => {
    const source = sources.find(row => row.resource_id === citation.resource_id);
    const quote = normalized(citation.quote);
    if (!source || !quote || !normalized(source.text).includes(quote)) {
      throw new Error('The generated answer contained an unsupported source quote. No answer was published. Please retry or ask your legal team.');
    }
    // Page values generated by a model are not independently established by text matching.
    return { ...citation, label: source.label, page: null, source_verified: true };
  });
}
