"use client";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
type Collection={collection:string;state:string;published_downloadable?:number;verified_indexed?:number;missing_ids?:string[]};
type Assessment={checked_at:string;scope:string;catalogue_complete:boolean;collections:Collection[]};
export function CorpusCoverage(){
 const [assessment,setAssessment]=useState<Assessment|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(signal?:AbortSignal){setBusy(true);try{const r=await fetch('/api/corpus-overview',{cache:'no-store',signal});if(!r.ok)throw new Error('Coverage check unavailable');const d=await r.json();setAssessment(d.assessment||null);setError('');}catch(e){if(!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'Coverage check unavailable');}finally{if(!signal?.aborted)setBusy(false);}}
 useEffect(()=>{const c=new AbortController();void load(c.signal);return()=>c.abort();},[]);
 return <section className="coverage-panel"><h2>Legal-source coverage</h2><p>Catalogue reconciliation records which published source documents are indexed. Court coverage, amendment effect and legal currentness require separate verification.</p><Button variant="outline" disabled={busy} onClick={()=>void load()}>Refresh coverage</Button>{assessment?<><p><b>{assessment.catalogue_complete?'Declared catalogue reconciled':'Declared catalogue has gaps'}</b> · Checked {new Date(assessment.checked_at).toLocaleString()}</p><p>{assessment.scope}</p><table><thead><tr><th>Collection</th><th>Published</th><th>Indexed</th><th>Missing</th></tr></thead><tbody>{assessment.collections.map(c=><tr key={c.collection}><td>{c.collection.replaceAll('_',' ')}</td><td>{c.published_downloadable??'Unknown'}</td><td>{c.verified_indexed??'Unknown'}</td><td>{c.state==='reconciled'?c.missing_ids?.length??0:'Check unavailable'}</td></tr>)}</tbody></table><p>These figures do not certify all-law coverage, OCR accuracy, or an authority's current good-law status.</p></>:<p>{busy?'Checking sources…':'No reconciled catalogue assessment is published yet.'}</p>}{error&&<p role="status">{error}</p>}</section>;
}
