"use client";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {workspace,type Identity} from "@/lib/legal/client";
type Entry={id:string;target_citation:string;judgment_citation:string;court:string;judgment_date:string;treatment:string;status:string;evidence_quote:string;review_note:string|null;reviewed_at:string|null;source_document_id:string;source_chunk_id:number};
type Chunk={id:number;content:string;page_number:number|null};
export function FirmCitator({identity}:{identity:Identity}){
 const [entries,setEntries]=useState<Entry[]>([]),[documents,setDocuments]=useState<{id:string;title:string}[]>([]),[chunks,setChunks]=useState<Chunk[]>([]),[document,setDocument]=useState(""),[chunk,setChunk]=useState(""),[target,setTarget]=useState(""),[judgment,setJudgment]=useState(""),[court,setCourt]=useState(""),[date,setDate]=useState(""),[quote,setQuote]=useState(""),[jurisdiction,setJurisdiction]=useState("TZ"),[treatment,setTreatment]=useState("distinguished"),[note,setNote]=useState(""),[filter,setFilter]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const reviewer=['owner','admin','partner'].includes(identity.role);
 async function load(){try{const [e,d]=await Promise.all([workspace<Entry[]>(identity,`citator_entries?organization_id=eq.${identity.organization_id}&order=updated_at.desc&limit=200`),workspace<{id:string;title:string}[]>(identity,`documents?select=id,title&organization_id=eq.${identity.organization_id}&status=eq.ready&order=title&limit=200`)]);setEntries(e);setDocuments(d);}catch(e){setMessage(e instanceof Error?e.message:'Could not load citator');}}
 useEffect(()=>{setEntries([]);setDocument('');setChunks([]);setQuote('');void load();},[identity.organization_id,identity.access_token]);
 useEffect(()=>{let live=true;setChunks([]);setChunk('');setQuote('');if(document)void workspace<Chunk[]>(identity,`document_chunks?select=id,content,page_number&document_id=eq.${document}&order=id&limit=1000`).then(c=>{if(live)setChunks(c);}).catch(e=>{if(live)setMessage(e.message);});return()=>{live=false;};},[document,identity.organization_id,identity.access_token]);
 async function submit(){setBusy(true);setMessage('');try{await workspace(identity,'citator_entries',{method:'POST',body:JSON.stringify({organization_id:identity.organization_id,source_document_id:document,source_chunk_id:Number(chunk),target_citation:target,judgment_citation:judgment,court,judgment_date:date,jurisdiction,treatment,evidence_quote:quote})});setMessage('Evidence submitted for firm review.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Submission failed');}finally{setBusy(false);}}
 async function review(id:string,status:string){setBusy(true);setMessage('');try{await workspace(identity,`citator_entries?id=eq.${id}&organization_id=eq.${identity.organization_id}`,{method:'PATCH',body:JSON.stringify({status,review_note:note})});await load();setMessage(status==='verified'?'Firm-reviewed treatment recorded.':'Evidence withdrawn.');}catch(e){setMessage(e instanceof Error?e.message:'Review failed');}finally{setBusy(false);}}
 const selected=chunks.find(c=>String(c.id)===chunk);
 return <section className="citator-panel"><h2>Judgment treatment citator</h2><p>Firm-reviewed evidence from judgments in your Vault. This records how a later judgment treated an authority. It does not certify that an authority is currently good law or cover every court. No result means treatment is unknown.</p><label className="citator-field"><span>Find an authority</span><Input aria-label="Filter citation" placeholder="Find a citation in loaded entries" value={filter} onChange={e=>setFilter(e.target.value)}/></label><Button variant="outline" disabled={busy} onClick={()=>void load()}>Refresh evidence</Button>
 {entries.filter(e=>e.target_citation.toLowerCase().includes(filter.toLowerCase())).map(e=><article key={e.id}><h3>{e.target_citation} — {e.treatment.replaceAll('_',' ')}</h3><p>{e.judgment_citation} · {e.court} · {e.judgment_date} · {e.status==='verified'?'Firm reviewed':e.status}</p><blockquote>{e.evidence_quote}</blockquote>{e.review_note&&<p>{e.review_note} · {e.reviewed_at}</p>}{reviewer&&e.status!=='withdrawn'&&<Button disabled={busy||note.trim().length<20} onClick={()=>void review(e.id,e.status==='verified'?'withdrawn':'verified')}>{e.status==='verified'?'Withdraw evidence':'Verify judgment treatment'}</Button>}</article>)}{!entries.length&&<div className="citator-empty"><b>No reviewed treatment evidence yet</b><p>Authority treatment is unknown. Add a judgment passage below and send it through your firm’s review process.</p></div>}
 {reviewer&&entries.some(e=>e.status!=="withdrawn")&&<label className="citator-field"><span>Reviewer note</span><Textarea aria-label="Judgment review note" placeholder="Review note: confirm the full judgment, authority identity, court, date and context supporting this treatment." value={note} onChange={e=>setNote(e.target.value)}/></label>}
 {identity.role!=='viewer'&&<details className="citator-submit"><summary>Add judgment evidence</summary><div className="citator-form"><h3>Submit judgment evidence</h3><p>Upload and process the judgment in Vault first. Select its passage and quote the treatment exactly. A firm owner, admin or partner must review it.</p><label className="citator-field"><span>Judgment document</span><select aria-label="Judgment document" value={document} onChange={e=>setDocument(e.target.value)}><option value="">Select judgment document</option>{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label><label className="citator-field"><span>Source passage</span><select aria-label="Judgment passage" value={chunk} onChange={e=>{setChunk(e.target.value);setQuote('');}}><option value="">Select passage</option>{chunks.map(c=><option key={c.id} value={c.id}>Page {c.page_number??'unknown'} · {c.content.slice(0,100)}</option>)}</select></label>{selected&&<pre style={{whiteSpace:'pre-wrap',maxHeight:220,overflow:'auto'}}>{selected.content}</pre>}
 <label className="citator-field"><span>Authority being treated</span><Input aria-label="Authority citation" placeholder="Authority being treated, e.g. neutral citation" value={target} onChange={e=>setTarget(e.target.value)}/></label><label className="citator-field"><span>Later judgment citation</span><Input aria-label="Later judgment citation" placeholder="Later judgment citation" value={judgment} onChange={e=>setJudgment(e.target.value)}/></label><label className="citator-field"><span>Court</span><Input aria-label="Court" placeholder="Court" value={court} onChange={e=>setCourt(e.target.value)}/></label><label className="citator-field"><span>Judgment date</span><Input aria-label="Judgment date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="citator-field"><span>Jurisdiction</span><select aria-label="Jurisdiction" value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)}>{['TZ','UK','EU','CA','AU','OTHER'].map(j=><option key={j}>{j}</option>)}</select></label><label className="citator-field"><span>Treatment</span><select aria-label="Judgment treatment" value={treatment} onChange={e=>setTreatment(e.target.value)}>{['followed','applied','distinguished','overruled','reversed','not_followed','questioned'].map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select></label><label className="citator-field"><span>Exact treatment quotation</span><Textarea aria-label="Exact judgment quotation" placeholder="Exact quotation from the selected passage, 30–4,000 characters" value={quote} onChange={e=>setQuote(e.target.value)}/></label><Button disabled={busy||!document||!chunk||quote.trim().length<30||quote.length>4000||target.trim().length<3||judgment.trim().length<3||court.trim().length<2||!date} onClick={()=>void submit()}>Submit for review</Button></div></details>}{message&&<p role="status">{message}</p>}</section>;
}
