"use client";

import { useEffect, useState, useRef } from "react";
import { FileText, LockKeyhole, LogIn, RefreshCw, ShieldCheck, Table2, Workflow } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { PortalAssistant } from "@/components/legal-eye-portal-assistant";

import { useClientSession, type ClientSession } from "@/lib/auth/use-client-session";

const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"";
const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"";
type Session=ClientSession;
type Portal={id:string;name:string;slug:string;status:string;branding:Record<string,unknown>};
type Resource={id:string;resource_type:"document"|"draft"|"review_table"|"workflow";resource_id:string;label:string|null;created_at:string};
function headers(s:Session,extra:Record<string,string>={}){return{apikey:K,Authorization:`Bearer ${s.access_token}`,...extra};}
async function rest<T>(s:Session,path:string):Promise<T>{const r=await fetch(`${U}/rest/v1/${path}`,{headers:headers(s),cache:"no-store"});const t=await r.text();const b=t?JSON.parse(t):null;if(!r.ok)throw new Error(b?.message||b?.hint||`Portal request failed (${r.status})`);return b as T;}

export function PortalGuestPro({slug}:{slug:string}){
 const key=`locke-portal:${slug}`;const {session,acceptSession,signOut,sessionError}=useClientSession(key);const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState<"signin"|"signup">("signin"),[portal,setPortal]=useState<Portal|null>(null),[resources,setResources]=useState<Resource[]>([]),[previews,setPreviews]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");

 useEffect(()=>{if(window.location.hash.includes("access_token=")||window.location.hash.includes("error=")){const params=new URLSearchParams(window.location.hash.slice(1));setMessage(params.get("error_description")||"Email confirmed. Sign in to open your invitation.");window.history.replaceState({},"",window.location.pathname);}},[]);
 const loadRevision=useRef(0);
 const redeem=async(s:Session)=>{const r=await fetch(`${U}/rest/v1/rpc/redeem_portal_invite_by_slug`,{method:"POST",headers:headers(s,{"content-type":"application/json"}),body:JSON.stringify({p_slug:slug})});const ok=r.ok?await r.json():false;if(!ok)throw new Error("This account does not have an active invitation to this portal.");};
 const load=async(s=session)=>{if(!s)return;const revision=++loadRevision.current;setBusy(true);setMessage("");try{setPortal(null);setResources([]);setPreviews({});await redeem(s);const rows=await rest<Portal[]>(s,`client_portals?select=id,name,slug,status,branding&slug=eq.${encodeURIComponent(slug)}&status=eq.active&limit=1`);if(revision!==loadRevision.current)return;const p=rows[0];if(!p)throw new Error("Portal is unavailable.");setPortal(p);const shared=await rest<Resource[]>(s,`portal_resources?select=id,resource_type,resource_id,label,created_at&portal_id=eq.${p.id}&order=created_at.desc`);if(revision!==loadRevision.current)return;setResources(shared);const next:Record<string,string>={};for(const r of shared){try{if(r.resource_type==="document"){const c=await rest<Array<{content:string;page_number:number|null}>>(s,`document_chunks?select=content,page_number&document_id=eq.${r.resource_id}&order=id.asc&limit=24`);next[r.id]=c.map(x=>`${x.page_number?`[p. ${x.page_number}] `:""}${x.content}`).join("\n\n").slice(0,9000);}else if(r.resource_type==="draft"){const d=await rest<Array<{content:{text?:string}}>>(s,`drafts?select=content&id=eq.${r.resource_id}&limit=1`);next[r.id]=String(d[0]?.content?.text||"").slice(0,9000);}else if(r.resource_type==="review_table"){const t=await rest<Array<{values:unknown}>>(s,`review_table_rows?select=values&review_table_id=eq.${r.resource_id}&order=position.asc&limit=30`);next[r.id]=JSON.stringify(t.map(x=>x.values),null,2).slice(0,9000);}else next[r.id]="This firm workflow is available in the assistant below. Its internal rules remain private.";}catch{next[r.id]="This resource is shared but its preview is not available.";}}if(revision===loadRevision.current)setPreviews(next);}catch(e){if(revision===loadRevision.current){setPortal(null);setResources([]);setPreviews({});setMessage(e instanceof Error?e.message:"Portal could not be loaded");}}finally{if(revision===loadRevision.current)setBusy(false);}};
 useEffect(()=>{if(session)void load(session);else{setPortal(null);setResources([]);setPreviews({});}},[session]);
 const authenticate=async()=>{setBusy(true);setMessage("");try{const endpoint=mode==="signin"?`${U}/auth/v1/token?grant_type=password`:`${U}/auth/v1/signup?redirect_to=${encodeURIComponent(window.location.origin+"/portal/"+slug)}`;const r=await fetch(endpoint,{method:"POST",headers:{apikey:K,"content-type":"application/json"},body:JSON.stringify({email,password})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.msg||data?.error_description||data?.message||"Authentication failed");const access=data.access_token||data.session?.access_token;if(!access){setMessage("Account created. Confirm your email, then return and sign in.");return;}acceptSession(data);setPassword("");}catch(e){setMessage(e instanceof Error?e.message:"Authentication failed");}finally{setBusy(false);}};
 const signout=()=>{loadRevision.current++;void signOut();setPortal(null);setResources([]);setPreviews({});};
 if(!session)return <main className="portal-guest-shell"><section className="portal-login"><div className="portal-brand"><span>L</span><div><b>LOCKE Portal</b><small>Secure client collaboration</small></div></div><h1>{mode==="signin"?"Open your client workspace":"Create your client account"}</h1><p>Use the email address your legal team invited. Your account only receives access to explicitly published material.</p><Input aria-label="Email" autoComplete="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/><Input aria-label="Password" autoComplete={mode==="signup"?"new-password":"current-password"} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><Button onClick={authenticate} disabled={busy||!email||password.length<(mode==="signup"?12:1)}><LogIn/> {busy?"Checking…":mode==="signin"?"Sign in":"Create account"}</Button>{mode==="signup"?<small>Use at least 12 characters.</small>:null}{message||sessionError?<p className="portal-message" role="status">{message||sessionError}</p>:null}<a href="/reset-password">Forgot password?</a><button className="portal-mode" onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?"First visit? Create your client account":"Already registered? Sign in"}</button></section></main>;
 const brand=String(portal?.branding?.brand_name||portal?.name||"LOCKE Portal"),tagline=String(portal?.branding?.tagline||"Secure legal collaboration");
 return <main className="portal-guest-shell portal-room"><header><div className="portal-brand"><span>{brand.slice(0,2).toUpperCase()}</span><div><b>{brand}</b><small>{tagline}</small></div></div><div className="row"><Badge><ShieldCheck/> Governed</Badge><Button variant="outline" onClick={signout}>Sign out</Button></div></header>{message&&!portal?<div className="portal-denied"><LockKeyhole/><h1>Access not available</h1><p>{message}</p></div>:<section><div className="portal-room-head"><div><span className="eyebrow">Shared legal workspace</span><h1>{portal?.name}</h1><p>{session.user.email}</p></div><Button variant="outline" onClick={()=>void load()}><RefreshCw/> Refresh</Button></div>{busy&&!portal?<div className="empty-live"><RefreshCw/><h2>Loading secure workspace…</h2></div>:null}{portal?<PortalAssistant key={portal.id} session={session} portal={portal} resources={resources}/>:null}<div className="portal-resource-grid">{resources.map(r=><article key={r.id}><div className="portal-resource-head">{r.resource_type==="workflow"?<Workflow/>:r.resource_type==="review_table"?<Table2/>:<FileText/>}<div><b>{r.label||"Shared legal work"}</b><small>{r.resource_type.replaceAll("_"," ")} · published {new Date(r.created_at).toLocaleDateString()}</small></div></div><pre>{previews[r.id]||"Loading preview…"}</pre></article>)}</div>{!resources.length&&!busy?<div className="empty-live"><ShieldCheck/><h2>No published resources yet</h2><p>Your legal team controls what appears in this workspace.</p></div>:null}</section>}</main>;
}

