"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, Database, Download, FileClock, KeyRound, RefreshCw, ShieldCheck, TriangleAlert, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { LiveIdentity } from "@/components/legal-eye-live";

const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"";const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"";
type Audit={id:number;user_id:string|null;action:string;object_type:string;object_id:string|null;metadata:Record<string,unknown>;created_at:string};
type Source={id:string;name:string;jurisdiction_code:string|null;policy_state:string;sync_enabled:boolean;last_synced_at:string|null;license_name:string|null;adapter_key:string;};
type Count={jurisdiction:string;documents:number;chunks:number};
async function rest<T>(identity:LiveIdentity,path:string):Promise<T>{const r=await fetch(`${U}/rest/v1/${path}`,{headers:{apikey:K,Authorization:`Bearer ${identity.access_token}`},cache:"no-store"});const t=await r.text();const b=t?JSON.parse(t):null;if(!r.ok)throw new Error(b?.message||`Trust request failed (${r.status})`);return b as T;}
async function count(identity:LiveIdentity,table:string,filter:string){const r=await fetch(`${U}/rest/v1/${table}?select=id&${filter}&limit=1`,{headers:{apikey:K,Authorization:`Bearer ${identity.access_token}`,Prefer:"count=exact"},cache:"no-store"});if(!r.ok)return 0;const range=r.headers.get("content-range")||"0/0";return Number(range.split("/").pop()||0)||0;}
export function TrustLive({identity,connect}:{identity:LiveIdentity|null;connect:()=>void}){const [audit,setAudit]=useState<Audit[]>([]),[sources,setSources]=useState<Source[]>([]),[counts,setCounts]=useState<Count[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");const blockers=useMemo(()=>sources.filter(s=>s.policy_state!=="approved"),[sources]);const healthy=useMemo(()=>sources.filter(s=>s.policy_state==="approved"&&s.sync_enabled),[sources]);
 const load=async()=>{if(!identity)return;setBusy(true);setError("");try{const [a,s]=await Promise.all([rest<Audit[]>(identity,`audit_events?select=id,user_id,action,object_type,object_id,metadata,created_at&organization_id=eq.${identity.organization_id}&order=created_at.desc&limit=250`),rest<Source[]>(identity,"source_registry?select=id,name,jurisdiction_code,policy_state,sync_enabled,last_synced_at,license_name,adapter_key&order=name.asc")]);setAudit(a);setSources(s);const jurisdictions=[...new Set(s.map(x=>x.jurisdiction_code).filter(Boolean))] as string[];const c:Count[]=[];for(const j of jurisdictions.slice(0,30)){const [documents,chunks]=await Promise.all([count(identity,"legal_documents",`jurisdiction_code=eq.${encodeURIComponent(j)}`),fetch(`${U}/rest/v1/legal_document_chunks?select=id&legal_document_id=in.(select-placeholder)&limit=0`).then(()=>0).catch(()=>0)]);c.push({jurisdiction:j,documents,chunks});}setCounts(c);}catch(e){setError(e instanceof Error?e.message:"Could not load trust data");}finally{setBusy(false);}};
 useEffect(()=>{void load();},[identity]);
 const exportAudit=()=>{const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),organization_id:identity?.organization_id,audit_events:audit,sources},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`legal-eye-audit-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);};
 if(!identity)return <div className="view-pad"><div className="section-header"><div><h1>Trust</h1><p>Security, governance, source policy and auditability.</p></div></div><div className="empty-live"><ShieldCheck/><h2>Sign in to inspect your firm audit trail</h2><Button onClick={connect}>Sign in</Button></div></div>;
 return <div className="view-pad"><div className="section-header"><div><h1>Trust</h1><p>Live audit trail, corpus rights, source health and governance controls.</p></div><div className="row"><Button variant="outline" onClick={()=>void load()} disabled={busy}><RefreshCw/> Refresh</Button><Button variant="outline" onClick={exportAudit}><Download/> Export audit</Button></div></div><div className="trust-kpis"><article><ShieldCheck/><span><b>{healthy.length}</b><small>approved live sources</small></span></article><article><TriangleAlert/><span><b>{blockers.length}</b><small>credential / licence gates</small></span></article><article><Activity/><span><b>{audit.length}</b><small>recent firm audit events</small></span></article><article><KeyRound/><span><b>RLS</b><small>org + portal isolation active</small></span></article></div>{error?<p className="portal-message">{error}</p>:null}<div className="trust-live-grid"><section><div className="subhead"><div><Database/><span><b>Corpus governance</b><small>Only approved sources may enter permanent search storage.</small></span></div></div><Table><TableHeader><TableRow><TableHead>Source</TableHead><TableHead>Jurisdiction</TableHead><TableHead>Policy</TableHead><TableHead>Sync</TableHead><TableHead>Last sync</TableHead></TableRow></TableHeader><TableBody>{sources.map(s=><TableRow key={s.id}><TableCell><b>{s.name}</b><small className="block-small">{s.license_name||"Licence not recorded"}</small></TableCell><TableCell>{s.jurisdiction_code||"Multi"}</TableCell><TableCell><Badge variant={s.policy_state==="approved"?"default":"outline"}>{s.policy_state.replaceAll("_"," ")}</Badge></TableCell><TableCell>{s.sync_enabled?"enabled":"gated"}</TableCell><TableCell>{s.last_synced_at?new Date(s.last_synced_at).toLocaleString():"Never"}</TableCell></TableRow>)}</TableBody></Table></section><section><div className="subhead"><div><FileClock/><span><b>Audit trail</b><small>Database-enforced mutation history for firm work.</small></span></div><Badge><Users/> {identity.role}</Badge></div><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Action</TableHead><TableHead>Object</TableHead><TableHead>User</TableHead></TableRow></TableHeader><TableBody>{audit.map(e=><TableRow key={e.id}><TableCell>{new Date(e.created_at).toLocaleString()}</TableCell><TableCell>{e.action}</TableCell><TableCell>{e.object_type}{e.object_id?<small className="block-small">{e.object_id.slice(0,12)}</small>:null}</TableCell><TableCell>{e.user_id?e.user_id.slice(0,8):"system"}</TableCell></TableRow>)}</TableBody></Table>{!audit.length&&!busy?<div className="empty-inline">No firm mutations recorded yet.</div>:null}</section></div></div>;
}
