"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Download, FileClock, FileText, Languages, MessageSquare, Save, ShieldCheck, Sparkles, UserRound, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import type { LiveIdentity } from "@/components/legal-eye-live";

type Props = { identity: LiveIdentity | null; connect: () => void };
type DraftRow = { id: string; title: string; document_type: string; content: { text?: string }; status: string; updated_at: string };
type VersionRow = { id: string; version_number: number; content: { text?: string }; created_at: string };
type CommentRow = { id: string; body: string; created_by: string; created_at: string; edited_at: string | null };

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? "";

function headers(identity: LiveIdentity, extra: Record<string, string> = {}) {
  return { apikey: SUPABASE_KEY, Authorization: `Bearer ${identity.access_token}`, ...extra };
}
async function rest<T>(identity: LiveIdentity, path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, { ...init, headers: headers(identity, init.headers as Record<string, string> || {}), cache: "no-store" });
  const text = await response.text(); const body = text ? JSON.parse(text) : null;
  if (!response.ok) throw new Error(body?.message || `Editor request failed (${response.status})`);
  return body as T;
}
async function transform(identity: LiveIdentity, operation: "improve"|"anonymize"|"translate"|"summarize", text: string, language?: string) {
  const response = await fetch("/api/legal-work", { method: "POST", headers: { Authorization: `Bearer ${identity.access_token}`, "content-type": "application/json" }, body: JSON.stringify({ action: "transform", organization_id: identity.organization_id, operation, text, language }) });
  const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Editor action failed"); return String(data.content || "");
}

export function EditorLive({ identity, connect }: Props) {
  const [drafts, setDrafts] = useState<DraftRow[]>([]), [draftId, setDraftId] = useState<string | null>(null), [title, setTitle] = useState("Untitled legal document"), [text, setText] = useState(""), [versions, setVersions] = useState<VersionRow[]>([]), [comments, setComments] = useState<CommentRow[]>([]), [comment, setComment] = useState(""), [suggestion, setSuggestion] = useState(""), [busy, setBusy] = useState(false), [dirty, setDirty] = useState(false);
  const current = drafts.find(d => d.id === draftId);
  const versionNumber = useMemo(() => versions.reduce((max, row) => Math.max(max, row.version_number), 0), [versions]);
  const loadDrafts = async () => { if (!identity) return; try { const rows = await rest<DraftRow[]>(identity, `drafts?select=id,title,document_type,content,status,updated_at&organization_id=eq.${identity.organization_id}&order=updated_at.desc&limit=30`); setDrafts(rows); if (!draftId && rows[0]) openDraft(rows[0], identity); } catch (error) { toast.error(error instanceof Error ? error.message : "Drafts could not be loaded"); } };
  const loadDetails = async (id: string, currentIdentity = identity) => { if (!currentIdentity) return; const [nextVersions, nextComments] = await Promise.all([rest<VersionRow[]>(currentIdentity, `draft_versions?select=id,version_number,content,created_at&draft_id=eq.${id}&order=version_number.desc&limit=30`), rest<CommentRow[]>(currentIdentity, `comments?select=id,body,created_by,created_at,edited_at&organization_id=eq.${currentIdentity.organization_id}&object_type=eq.draft&object_id=eq.${id}&order=created_at.asc`)]); setVersions(nextVersions); setComments(nextComments); };
  const openDraft = (draft: DraftRow, currentIdentity = identity) => { setDraftId(draft.id); setTitle(draft.title); setText(draft.content?.text || ""); setSuggestion(""); setDirty(false); void loadDetails(draft.id, currentIdentity); };
  useEffect(() => { void loadDrafts(); }, [identity]);
  useEffect(() => { if (!identity || !draftId) return; const timer = window.setInterval(() => void loadDetails(draftId), 8000); return () => window.clearInterval(timer); }, [identity, draftId]);
  const newDraft = () => { setDraftId(null); setTitle("Untitled legal document"); setText(""); setVersions([]); setComments([]); setSuggestion(""); setDirty(true); };
  const save = async () => { if (!identity) return connect(); if (!title.trim()) return toast.error("Give the document a title."); setBusy(true); try { let id = draftId; if (!id) { const created = await rest<DraftRow[]>(identity, "drafts", { method: "POST", headers: { "content-type": "application/json", Prefer: "return=representation" }, body: JSON.stringify({ organization_id: identity.organization_id, created_by: identity.user.id, title: title.trim(), document_type: "legal_document", jurisdiction_codes: ["TZ"], content: { text }, status: "draft", metadata: { editor: "legal-eye", collaborative: true } }) }); id = created[0].id; setDraftId(id); } else { await rest(identity, `drafts?id=eq.${id}`, { method: "PATCH", headers: { "content-type": "application/json", Prefer: "return=minimal" }, body: JSON.stringify({ title: title.trim(), content: { text }, updated_at: new Date().toISOString() }) }); }
      const existing = await rest<Array<{ version_number: number }>>(identity, `draft_versions?select=version_number&draft_id=eq.${id}&order=version_number.desc&limit=1`); const next = (existing[0]?.version_number || 0) + 1;
      await rest(identity, "draft_versions", { method: "POST", headers: { "content-type": "application/json", Prefer: "return=minimal" }, body: JSON.stringify({ draft_id: id, version_number: next, content: { text }, created_by: identity.user.id }) }); setDirty(false); toast.success(`Saved version ${next}`); await loadDrafts(); await loadDetails(id);
    } catch (error) { toast.error(error instanceof Error ? error.message : "Document could not be saved"); } finally { setBusy(false); } };
  const runAction = async (operation: "improve"|"anonymize"|"translate"|"summarize") => { if (!identity) return connect(); if (!text.trim()) return toast.error("Add document text first."); setBusy(true); try { setSuggestion(await transform(identity, operation, text, operation === "translate" ? "Kiswahili" : undefined)); toast.success(`${operation} suggestion ready`, { description: "Review the proposed change before accepting it." }); } catch (error) { toast.error(error instanceof Error ? error.message : "Editor action failed"); } finally { setBusy(false); } };
  const accept = () => { if (!suggestion) return; setText(suggestion); setSuggestion(""); setDirty(true); };
  const postComment = async () => { if (!identity) return connect(); if (!draftId) return toast.error("Save the document before commenting."); if (!comment.trim()) return; try { await rest(identity, "comments", { method: "POST", headers: { "content-type": "application/json", Prefer: "return=minimal" }, body: JSON.stringify({ organization_id: identity.organization_id, object_type: "draft", object_id: draftId, body: comment.trim(), created_by: identity.user.id }) }); setComment(""); await loadDetails(draftId); } catch (error) { toast.error(error instanceof Error ? error.message : "Comment could not be posted"); } };
  const restore = (version: VersionRow) => { setText(version.content?.text || ""); setSuggestion(""); setDirty(true); toast(`Version ${version.version_number} loaded into the editor`); };
  const exportWord = () => { const safeTitle = title.replace(/[<>]/g, ""); const html = `<!doctype html><html><head><meta charset="utf-8"><title>${safeTitle}</title><style>body{font-family:Cambria,Georgia,serif;font-size:11pt;line-height:1.5;margin:1in}h1{font-size:18pt}p{margin:0 0 10pt;white-space:pre-wrap}</style></head><body><h1>${safeTitle}</h1><p>${text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;")}</p></body></html>`; const url = URL.createObjectURL(new Blob([html], { type: "application/msword" })); const a = document.createElement("a"); a.href = url; a.download = `${safeTitle || "legal-eye-document"}.doc`; a.click(); URL.revokeObjectURL(url); toast.success("Word document exported"); };
  return <div className="editor-live"><div className="section-header"><div><h1>Editor</h1><p>Draft with firm context, version every save, collaborate through comments, apply AI changes only after review, then export to Word.</p></div><div className="row"><Button variant="outline" onClick={newDraft}>New</Button><Button variant="outline" onClick={exportWord} disabled={!text.trim()}><Download/> Word</Button><Button onClick={save} disabled={busy || !dirty}><Save/> {busy ? "Working…" : dirty ? "Save version" : `Saved v${versionNumber}`}</Button></div></div>
    {!identity ? <div className="empty-live"><ShieldCheck/><h2>Secure editor</h2><p>Sign in to create versioned firm work product.</p><Button onClick={connect}>Sign in</Button></div> : <div className="editor-live-grid"><aside className="editor-library"><span className="eyebrow">Documents</span>{drafts.map(d => <button className={draftId === d.id ? "active" : ""} key={d.id} onClick={() => openDraft(d)}><FileText/><span><b>{d.title}</b><small>{new Date(d.updated_at).toLocaleString()}</small></span></button>)}</aside><section className="editor-document"><Input className="editor-title" value={title} onChange={e => { setTitle(e.target.value); setDirty(true); }}/><Textarea aria-label="Document editor" value={text} onChange={e => { setText(e.target.value); setDirty(true); }} placeholder="Draft, paste or generate legal work product here…"/><div className="editor-actions"><Button variant="outline" onClick={() => void runAction("improve")} disabled={busy}><Sparkles/> Improve writing</Button><Button variant="outline" onClick={() => void runAction("anonymize")} disabled={busy}><UserRound/> Anonymize</Button><Button variant="outline" onClick={() => void runAction("translate")} disabled={busy}><Languages/> Translate to Kiswahili</Button><Button variant="outline" onClick={() => void runAction("summarize")} disabled={busy}><FileText/> Summarize</Button></div>{suggestion ? <div className="editor-suggestion"><div><span className="eyebrow">AI proposal · lawyer review required</span><div className="row"><Button size="sm" onClick={accept}><Check/> Accept</Button><Button size="sm" variant="outline" onClick={() => setSuggestion("")}><X/> Reject</Button></div></div><pre>{suggestion}</pre></div> : null}</section><aside className="editor-collab"><span className="eyebrow">Collaboration</span><div className="comment-compose"><Textarea value={comment} onChange={e => setComment(e.target.value)} placeholder="Comment on this draft…"/><Button size="sm" onClick={postComment} disabled={!draftId || !comment.trim()}><MessageSquare/> Comment</Button></div><div className="comments">{comments.map(c => <article key={c.id}><i><UserRound/></i><div><b>{c.created_by === identity.user.id ? "You" : "Collaborator"}</b><p>{c.body}</p><small>{new Date(c.created_at).toLocaleString()}</small></div></article>)}</div><hr/><span className="eyebrow">Version history</span><div className="version-list">{versions.map(v => <button key={v.id} onClick={() => restore(v)}><FileClock/><span><b>Version {v.version_number}</b><small>{new Date(v.created_at).toLocaleString()}</small></span></button>)}</div></aside></div>}
  </div>;
}
