-- Fresh-project foundation. Apply before the historical incremental migrations.
begin;
create schema if not exists private;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists vector with schema extensions;
create type public.org_role as enum ('owner','admin','partner','associate','paralegal','viewer');
create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,jurisdiction_codes text[] not null default '{TZ}',created_by uuid references auth.users(id),metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.organization_members(organization_id uuid references public.organizations(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role public.org_role not null default 'associate',is_active boolean not null default true,created_at timestamptz not null default now(),primary key(organization_id,user_id));
create table public.matters(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null,client_name text,description text,practice_area text,status text not null default 'active',jurisdiction_codes text[] not null default '{TZ}',is_restricted boolean not null default false,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.matter_members(matter_id uuid references public.matters(id) on delete cascade,user_id uuid references auth.users(id),primary key(matter_id,user_id));
create table public.documents(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),title text not null,file_name text,mime_type text,storage_path text,size_bytes bigint,status text not null default 'uploaded',jurisdiction_codes text[] not null default '{TZ}',uploaded_by uuid references auth.users(id),content_hash text,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.document_chunks(id bigint generated always as identity primary key,document_id uuid not null references public.documents(id) on delete cascade,chunk_index integer,page_number integer,clause_number text,paragraph_number text,content text not null,token_count integer,metadata jsonb not null default '{}',embedding extensions.vector(1536),search_vector tsvector generated always as (to_tsvector('simple',content)) stored,created_at timestamptz not null default now());
create table public.source_registry(id uuid primary key default gen_random_uuid(),name text not null unique,jurisdiction_code text,authority_level text,base_url text,adapter_key text,content_types text[] not null default '{}',policy_state text not null default 'pending',discovery_allowed boolean not null default false,individual_retrieval_allowed boolean not null default false,commercial_display_allowed boolean not null default false,bulk_ingestion_allowed boolean not null default false,embedding_allowed boolean not null default false,computational_analysis_allowed boolean not null default false,attribution_required boolean not null default true,attribution_text text,license_name text,license_url text,api_docs_url text,sync_enabled boolean not null default false,refresh_interval interval not null default '1 day',last_legal_review timestamptz,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.legal_documents(id uuid primary key default gen_random_uuid(),source_id uuid references public.source_registry(id),canonical_source_id text,title text not null,citation text,court text,jurisdiction_code text not null,document_type text not null default 'legislation',canonical_url text,current_status text,effective_from date,effective_to date,published_at timestamptz,content_hash text,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
-- Historical retrieval RPCs return bigint IDs and refer to these legacy columns.
create table public.legal_document_chunks(id bigint generated always as identity primary key,legal_document_id uuid not null references public.legal_documents(id) on delete cascade,content text not null,paragraph_number text,page_number integer,token_count integer,metadata jsonb not null default '{}',embedding extensions.vector(1536),created_at timestamptz not null default now());
create table public.authorities(id uuid primary key default gen_random_uuid(),legal_document_id uuid references public.legal_documents(id),title text,citation text,jurisdiction_code text,status text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.ingestion_jobs(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id),source_id uuid references public.source_registry(id),document_id uuid references public.documents(id) on delete cascade,job_type text not null,status text not null default 'queued',progress numeric not null default 0,payload jsonb not null default '{}',metadata jsonb not null default '{}',error_message text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),started_at timestamptz,completed_at timestamptz);
create table public.drafts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),title text not null,document_type text,jurisdiction_codes text[] not null default '{TZ}',content jsonb not null default '{}',status text not null default 'draft');
create table public.research_sessions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),title text not null,query text not null,answer_markdown text,jurisdiction_codes text[] not null default '{TZ}',use_firm_knowledge boolean not null default false,metadata jsonb not null default '{}');
create table public.firm_templates(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),name text not null,description text,content jsonb not null default '{}',document_type text,jurisdiction_codes text[] not null default '{TZ}',status text not null default 'draft');
create table public.workflow_skills(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),name text not null,description text,instructions text not null,trigger_phrase text,tool_policy jsonb not null default '{}',is_active boolean not null default true);
create table public.review_tables(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),name text not null,description text,columns jsonb not null default '[]');
create table public.checklists(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),name text not null,description text);
create table public.agent_runs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),objective text not null,status text not null default 'running',plan jsonb not null default '[]',result jsonb,started_at timestamptz,completed_at timestamptz);
create table public.review_projects(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),document_id uuid references public.documents(id),overall_risk text,status text not null default 'complete',summary jsonb not null default '{}');
create table public.comments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),object_type text not null,object_id uuid not null,body text not null);
create table public.client_portals(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),name text not null,slug text not null unique,status text not null default 'active',branding jsonb not null default '{}');
create table public.audit_logs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),matter_id uuid references public.matters(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),actor_id uuid references auth.users(id),action text,object_type text,object_id uuid,metadata jsonb not null default '{}');
create table public.draft_versions(id uuid primary key default gen_random_uuid(),draft_id uuid not null references public.drafts(id) on delete cascade,version_number integer not null,content jsonb not null,created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(draft_id,version_number));
create table public.review_findings(id uuid primary key default gen_random_uuid(),review_project_id uuid not null references public.review_projects(id) on delete cascade,title text not null,risk text not null default 'info',clause_ref text,why_it_matters text,original_text text,suggested_text text,status text not null default 'open',metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.review_table_rows(id uuid primary key default gen_random_uuid(),review_table_id uuid not null references public.review_tables(id) on delete cascade,document_id uuid references public.documents(id),position integer not null default 0,values jsonb not null default '{}',review_status text not null default 'needs_review',locked_fields text[] not null default '{}',created_at timestamptz not null default now());
create table public.checklist_items(id uuid primary key default gen_random_uuid(),checklist_id uuid not null references public.checklists(id) on delete cascade,title text not null,source_clause text,source_page integer,status text not null default 'pending',priority text not null default 'medium',category text,notes text,position integer not null default 0,due_date date,assignee_id uuid references auth.users(id),created_at timestamptz not null default now());
create table public.portal_members(portal_id uuid references public.client_portals(id) on delete cascade,user_id uuid references auth.users(id),role text not null default 'guest',created_at timestamptz not null default now(),primary key(portal_id,user_id));
create table public.portal_invites(id uuid primary key default gen_random_uuid(),portal_id uuid not null references public.client_portals(id) on delete cascade,email text not null,role text not null default 'guest',created_by uuid references auth.users(id),expires_at timestamptz not null default now()+interval '7 days',accepted_at timestamptz,created_at timestamptz not null default now(),unique(portal_id,email));
create table public.portal_resources(id uuid primary key default gen_random_uuid(),portal_id uuid not null references public.client_portals(id) on delete cascade,resource_type text not null,resource_id uuid not null,label text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(portal_id,resource_type,resource_id));
create table public.portal_conversations(id uuid primary key default gen_random_uuid(),portal_id uuid not null references public.client_portals(id) on delete cascade,title text,created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.portal_messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.portal_conversations(id) on delete cascade,user_id uuid references auth.users(id),role text not null,content text not null,citations jsonb not null default '[]',created_at timestamptz not null default now());
create table public.portal_runs(id uuid primary key default gen_random_uuid(),portal_id uuid not null references public.client_portals(id) on delete cascade,workflow_id uuid,status text not null default 'running',started_by uuid references auth.users(id),input jsonb not null default '{}',result jsonb,output jsonb,completed_at timestamptz,created_at timestamptz not null default now());
create function private.is_org_member(p_org uuid) returns boolean language sql stable security definer set search_path='' as $$select auth.uid() is not null and exists(select 1 from public.organization_members where organization_id=p_org and user_id=auth.uid() and is_active)$$;
create function private.org_role_for(p_org uuid) returns public.org_role language sql stable security definer set search_path='' as $$select role from public.organization_members where organization_id=p_org and user_id=auth.uid() and is_active$$;
create function private.has_matter_access(p_matter uuid) returns boolean language sql stable security definer set search_path='' as $$select auth.uid() is not null and exists(select 1 from public.matters m where m.id=p_matter and private.is_org_member(m.organization_id) and (not m.is_restricted or m.created_by=auth.uid() or exists(select 1 from public.matter_members mm where mm.matter_id=m.id and mm.user_id=auth.uid())))$$;
create function private.has_portal_access(p_portal uuid) returns boolean language sql stable security definer set search_path='' as $$select auth.uid() is not null and exists(select 1 from public.client_portals p where p.id=p_portal and ((private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id))) or (p.status='active' and exists(select 1 from public.portal_members pm where pm.portal_id=p.id and pm.user_id=auth.uid()))))$$;
create function private.shared_resource(p_type text,p_id uuid) returns boolean language sql stable security definer set search_path='' as $$select auth.uid() is not null and exists(select 1 from public.portal_resources r join public.client_portals p on p.id=r.portal_id join public.portal_members pm on pm.portal_id=p.id where r.resource_type=p_type and r.resource_id=p_id and p.status='active' and pm.user_id=auth.uid())$$;
create function private.can_view_document(p_id uuid) returns boolean language sql stable security definer set search_path='' as $$select auth.uid() is not null and (exists(select 1 from public.documents d where d.id=p_id and private.is_org_member(d.organization_id) and (d.matter_id is null or private.has_matter_access(d.matter_id))) or private.shared_resource('document',p_id))$$;
revoke all on schema private from public;
grant usage on schema private to authenticated,service_role;
revoke all on all functions in schema private from public,anon;
grant execute on all functions in schema private to authenticated,service_role;
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.matters enable row level security;
alter table public.matter_members enable row level security;
alter table public.documents enable row level security;
alter table public.document_chunks enable row level security;
alter table public.source_registry enable row level security;
alter table public.legal_documents enable row level security;
alter table public.legal_document_chunks enable row level security;
alter table public.authorities enable row level security;
alter table public.ingestion_jobs enable row level security;
alter table public.drafts enable row level security;
alter table public.research_sessions enable row level security;
alter table public.firm_templates enable row level security;
alter table public.workflow_skills enable row level security;
alter table public.review_tables enable row level security;
alter table public.checklists enable row level security;
alter table public.agent_runs enable row level security;
alter table public.review_projects enable row level security;
alter table public.comments enable row level security;
alter table public.client_portals enable row level security;
alter table public.audit_logs enable row level security;
alter table public.draft_versions enable row level security;
alter table public.review_findings enable row level security;
alter table public.review_table_rows enable row level security;
alter table public.checklist_items enable row level security;
alter table public.portal_members enable row level security;
alter table public.portal_invites enable row level security;
alter table public.portal_resources enable row level security;
alter table public.portal_conversations enable row level security;
alter table public.portal_messages enable row level security;
alter table public.portal_runs enable row level security;
grant select on public.organizations,public.organization_members to authenticated;
create policy org_read on public.organizations for select to authenticated using(private.is_org_member(id));
create policy member_read on public.organization_members for select to authenticated using(private.is_org_member(organization_id));
create policy matter_read on public.matters for select to authenticated using(private.is_org_member(organization_id) and (not is_restricted or created_by=auth.uid() or exists(select 1 from public.matter_members mm where mm.matter_id=matters.id and mm.user_id=auth.uid())));
create policy matter_insert on public.matters for insert to authenticated with check(private.is_org_member(organization_id) and created_by=auth.uid());
create policy matter_update on public.matters for update to authenticated using(private.has_matter_access(id)) with check(private.is_org_member(organization_id) and private.has_matter_access(id));
create policy matter_members_read on public.matter_members for select to authenticated using(private.has_matter_access(matter_id));
grant select,insert,update on public.matters to authenticated;
grant select on public.matter_members to authenticated;
create policy documents_read on public.documents for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) or private.shared_resource('document',id));
create policy documents_insert on public.documents for insert to authenticated with check(private.is_org_member(organization_id) and uploaded_by=auth.uid() and (matter_id is null or private.has_matter_access(matter_id)));
create policy documents_update on public.documents for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy documents_delete on public.documents for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and (uploaded_by=auth.uid() or private.org_role_for(organization_id) in ('owner','admin','partner')));
grant select,insert,update,delete on public.documents to authenticated;
create policy chunks_read on public.document_chunks for select to authenticated using(private.can_view_document(document_id));
grant select,insert,delete on public.document_chunks to authenticated;
create policy drafts_read on public.drafts for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) or private.shared_resource('draft',id));
create policy drafts_insert on public.drafts for insert to authenticated with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and created_by=auth.uid());
create policy drafts_update on public.drafts for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy drafts_delete on public.drafts for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
grant select,insert,update,delete on public.drafts to authenticated;
create policy research_sessions_read on public.research_sessions for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))));
create policy research_sessions_insert on public.research_sessions for insert to authenticated with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and created_by=auth.uid());
create policy research_sessions_update on public.research_sessions for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy research_sessions_delete on public.research_sessions for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
grant select,insert,update,delete on public.research_sessions to authenticated;
create policy firm_templates_read on public.firm_templates for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))));
create policy firm_templates_insert on public.firm_templates for insert to authenticated with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and created_by=auth.uid());
create policy firm_templates_update on public.firm_templates for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy firm_templates_delete on public.firm_templates for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
grant select,insert,update,delete on public.firm_templates to authenticated;
create policy workflow_skills_read on public.workflow_skills for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))));
create policy workflow_skills_insert on public.workflow_skills for insert to authenticated with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and created_by=auth.uid());
create policy workflow_skills_update on public.workflow_skills for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy workflow_skills_delete on public.workflow_skills for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
grant select,insert,update,delete on public.workflow_skills to authenticated;
create policy review_tables_read on public.review_tables for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) or private.shared_resource('review_table',id));
create policy review_tables_insert on public.review_tables for insert to authenticated with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and created_by=auth.uid());
create policy review_tables_update on public.review_tables for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy review_tables_delete on public.review_tables for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
grant select,insert,update,delete on public.review_tables to authenticated;
create policy checklists_read on public.checklists for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))));
create policy checklists_insert on public.checklists for insert to authenticated with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and created_by=auth.uid());
create policy checklists_update on public.checklists for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy checklists_delete on public.checklists for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
grant select,insert,update,delete on public.checklists to authenticated;
create policy agent_runs_read on public.agent_runs for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))));
create policy agent_runs_insert on public.agent_runs for insert to authenticated with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and created_by=auth.uid());
create policy agent_runs_update on public.agent_runs for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy agent_runs_delete on public.agent_runs for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
grant select,insert,update,delete on public.agent_runs to authenticated;
create policy review_projects_read on public.review_projects for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))));
create policy review_projects_insert on public.review_projects for insert to authenticated with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and created_by=auth.uid());
create policy review_projects_update on public.review_projects for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy review_projects_delete on public.review_projects for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
grant select,insert,update,delete on public.review_projects to authenticated;
create policy comments_read on public.comments for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))));
create policy comments_insert on public.comments for insert to authenticated with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and created_by=auth.uid());
create policy comments_update on public.comments for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy comments_delete on public.comments for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
grant select,insert,update,delete on public.comments to authenticated;
create policy client_portals_read on public.client_portals for select to authenticated using((private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) or private.has_portal_access(id));
create policy client_portals_insert on public.client_portals for insert to authenticated with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)) and created_by=auth.uid());
create policy client_portals_update on public.client_portals for update to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id))) with check(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
create policy client_portals_delete on public.client_portals for delete to authenticated using(private.is_org_member(organization_id) and (matter_id is null or private.has_matter_access(matter_id)));
grant select,insert,update,delete on public.client_portals to authenticated;
create policy audit_read on public.audit_logs for select to authenticated using(private.org_role_for(organization_id) in ('owner','admin'));
grant select on public.audit_logs to authenticated;
create policy draft_versions_read on public.draft_versions for select to authenticated using(exists(select 1 from public.drafts p where p.id=draft_id));
create policy draft_versions_write on public.draft_versions for all to authenticated using(exists(select 1 from public.drafts p where p.id=draft_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id)))) with check(exists(select 1 from public.drafts p where p.id=draft_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id))));
grant select,insert,update,delete on public.draft_versions to authenticated;
create policy review_findings_read on public.review_findings for select to authenticated using(exists(select 1 from public.review_projects p where p.id=review_project_id));
create policy review_findings_write on public.review_findings for all to authenticated using(exists(select 1 from public.review_projects p where p.id=review_project_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id)))) with check(exists(select 1 from public.review_projects p where p.id=review_project_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id))));
grant select,insert,update,delete on public.review_findings to authenticated;
create policy review_table_rows_read on public.review_table_rows for select to authenticated using(exists(select 1 from public.review_tables p where p.id=review_table_id));
create policy review_table_rows_write on public.review_table_rows for all to authenticated using(exists(select 1 from public.review_tables p where p.id=review_table_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id)))) with check(exists(select 1 from public.review_tables p where p.id=review_table_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id))));
grant select,insert,update,delete on public.review_table_rows to authenticated;
create policy checklist_items_read on public.checklist_items for select to authenticated using(exists(select 1 from public.checklists p where p.id=checklist_id));
create policy checklist_items_write on public.checklist_items for all to authenticated using(exists(select 1 from public.checklists p where p.id=checklist_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id)))) with check(exists(select 1 from public.checklists p where p.id=checklist_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id))));
grant select,insert,update,delete on public.checklist_items to authenticated;
create policy portal_members_read on public.portal_members for select to authenticated using(private.has_portal_access(portal_id));
create policy portal_members_write on public.portal_members for all to authenticated using(exists(select 1 from public.client_portals p where p.id=portal_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id)))) with check(exists(select 1 from public.client_portals p where p.id=portal_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id))));
grant select,insert,update,delete on public.portal_members to authenticated;
create policy portal_invites_read on public.portal_invites for select to authenticated using(private.has_portal_access(portal_id));
create policy portal_invites_write on public.portal_invites for all to authenticated using(exists(select 1 from public.client_portals p where p.id=portal_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id)))) with check(exists(select 1 from public.client_portals p where p.id=portal_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id))));
grant select,insert,update,delete on public.portal_invites to authenticated;
create policy portal_resources_read on public.portal_resources for select to authenticated using(private.has_portal_access(portal_id));
create policy portal_resources_write on public.portal_resources for all to authenticated using(exists(select 1 from public.client_portals p where p.id=portal_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id)))) with check(exists(select 1 from public.client_portals p where p.id=portal_id and private.is_org_member(p.organization_id) and (p.matter_id is null or private.has_matter_access(p.matter_id))));
grant select,insert,update,delete on public.portal_resources to authenticated;
create policy portal_conversations_read on public.portal_conversations for select to authenticated using(private.has_portal_access(portal_id));
create policy portal_conversations_write on public.portal_conversations for all to authenticated using(private.has_portal_access(portal_id)) with check(private.has_portal_access(portal_id));
grant select,insert,update,delete on public.portal_conversations to authenticated;
create policy portal_runs_read on public.portal_runs for select to authenticated using(private.has_portal_access(portal_id));
create policy portal_runs_write on public.portal_runs for all to authenticated using(private.has_portal_access(portal_id)) with check(private.has_portal_access(portal_id));
grant select,insert,update,delete on public.portal_runs to authenticated;
create policy portal_messages_access on public.portal_messages for all to authenticated using(exists(select 1 from public.portal_conversations c where c.id=conversation_id and private.has_portal_access(c.portal_id))) with check(exists(select 1 from public.portal_conversations c where c.id=conversation_id and private.has_portal_access(c.portal_id)));
grant select,insert on public.portal_messages to authenticated;
create policy sources_read on public.source_registry for select to authenticated using(true);
create policy authorities_read on public.authorities for select to authenticated using(true);
grant select on public.source_registry,public.legal_documents,public.legal_document_chunks,public.authorities to authenticated;
grant all on all tables in schema public to service_role;
grant usage,select on all sequences in schema public to authenticated,service_role;
create index document_chunks_search_idx on public.document_chunks using gin(search_vector);
create index organization_members_user_idx on public.organization_members(user_id,organization_id) where is_active;
create index drafts_org_idx on public.drafts(organization_id);
create index research_sessions_org_idx on public.research_sessions(organization_id);
create index firm_templates_org_idx on public.firm_templates(organization_id);
create index workflow_skills_org_idx on public.workflow_skills(organization_id);
create index review_tables_org_idx on public.review_tables(organization_id);
create index checklists_org_idx on public.checklists(organization_id);
create index agent_runs_org_idx on public.agent_runs(organization_id);
create index review_projects_org_idx on public.review_projects(organization_id);
create index comments_org_idx on public.comments(organization_id);
create index client_portals_org_idx on public.client_portals(organization_id);
create index audit_logs_org_idx on public.audit_logs(organization_id);
commit;
